services:
  user-service:
    image: w3-user-service:latest
    container_name: user-service
    build:
      context: ./user-service
      dockerfile: Dockerfile
    env_file: ./user-service/.env
    networks:
      - service-network
    depends_on:
      - eureka-naming-server
      - config-server
  order-service:
    image: w3-order-service:latest
    container_name: order-service
    build:
      context: ./order-service
      dockerfile: Dockerfile
    env_file:
      - ./order-service/.env
    networks:
      - service-network
    depends_on:
      - eureka-naming-server
      - config-server
  product-service:
    image: w3-product-service:latest
    container_name: product-service
    build:
      context: ./product-service
      dockerfile: Dockerfile
    env_file:
      - ./product-service/.env
    networks:
      - service-network
    depends_on:
      - eureka-naming-server
      - config-server
  gateway:
    image: w3-gateway:latest
    container_name: gateway
    build:
      context: ./gateway
      dockerfile: Dockerfile
    env_file:
      - ./gateway/.env
    networks:
      - service-network
    ports:
      - "8005:8005"
    depends_on:
      - eureka-naming-server
      - config-server
      - product-service
      - order-service
      - user-service
  eureka-naming-server:
    image: w3-eureka-naming-server:latest
    container_name: eureka-naming-server
    build:
      context: ./eureka-naming-server
      dockerfile: Dockerfile
    env_file:
      - ./eureka-naming-server/.env
    ports:
      - "8005:8005"
    networks:
      - service-network
  config-server:
    image: w3-config-server:latest
    container_name: config-server
    build:
      context: ./spring-cloud-config-server
      dockerfile: Dockerfile
    env_file:
      - ./spring-cloud-config-server/.env
    networks:
      - service-network

networks:
  service-network:
    driver: bridge